"""Add cascade delete to Frequency subclasses

Revision ID: 2db3fa46306a
Revises: 4766206eff54
Create Date: 2024-10-18 10:26:36.711279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db3fa46306a'
down_revision: Union[str, None] = '4766206eff54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "fk":
    "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_frequencies", naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_daily_frequencies_id_frequencies", type_='foreignkey')
        batch_op.create_foreign_key('daily_frequencies', 'frequencies', ['id'], ['id'], ondelete='cascade')
    with op.batch_alter_table("weekly_frequencies", naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_weekly_frequencies_id_frequencies", type_='foreignkey')
        batch_op.create_foreign_key('weekly_frequencies', 'frequencies', ['id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weekly_frequencies", naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_weekly_frequencies_id_frequencies', type_='foreignkey')
        batch_op.create_foreign_key('weekly_frequencies', 'frequencies', ['id'], ['id'])
    with op.batch_alter_table("daily_frequencies", naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_daily_frequencies_id_frequencies', type_='foreignkey')
        batch_op.create_foreign_key('daily_frequencies', 'frequencies', ['id'], ['id'])
    # ### end Alembic commands ###
