"""Add Execution Windows

Revision ID: 9fa77f2dac91
Revises: 796eb3dcecda
Create Date: 2024-09-29 14:32:15.984444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa77f2dac91'
down_revision: Union[str, None] = '796eb3dcecda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'HIT', 'SKIPPED', 'MISSED', name='executionwindowstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table("executions") as batch_op:
        batch_op.add_column(sa.Column('execution_window_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('execution_to_execution_window', 'execution_windows', ['execution_window_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions") as batch_op:
        batch_op.drop_constraint('execution_to_execution_window', type_='foreignkey')
        batch_op.drop_column('execution_window_id')
    op.drop_table('execution_windows')
    # ### end Alembic commands ###
